language: node_js
node_js:
  - 0.10
services:
  - mongodb
script: ./node_modules/mocha/bin/mocha --growl --reporter spec test/test.*.js
env: NODE_ENV=travisci MONGODB_URL='mongodb://127.0.0.1/masalanpelto-travisci' TEST_PASSWORD_ASUKAS=asukas TEST_PASSWORD_HALLITUS=hallitus TEST_PASSWORD_ADMIN=admin PASSWORD_HASH_ASUKAS=JDJhJDEwJGhIR0tyc0JaUi5iZ25KN2N5dS9CUGVVS2M3ZzBDNjVEaVc0MmJqVW1tM2x0QXkxOTZqWlND PASSWORD_HASH_HALLITUS=JDJhJDEwJFhmTVA4L3o2VnlJT21LMmMxRjQyUS5HSThaamdsMnVLSlMzcEdxMEpRRXAxUklLNFZ3SVVl PASSWORD_HASH_ADMIN=JDJhJDEwJGVYNHE4QTM4QUgyRXNwYS9KTkYydGU0TkFxNDRLUkNPSk14R2JSUUxmdWM4ZW5yYUgzcHh1 AWS_ACCESS_KEY_ID=invalid AWS_SECRET_ACCESS_KEY=invalid S3_BUCKET_NAME=invalid
